package simplehttpserver;

import com.kttdevelopment.simplehttpserver.*;
import com.kttdevelopment.webdir.server.httpserver.SimpleHttpServerUnmodifiable;
import com.sun.net.httpserver.HttpExchange;
import org.junit.*;

import java.io.IOException;

public class UnmodifiableServerTests {

    @Test
    public void testValid() throws IOException{
        SimpleHttpServer server = SimpleHttpServer.create();
        try{
            server.getAddress();
        }catch(final UnsupportedOperationException ignored){
            Assert.fail("Supported operation address was blocked");
        }
        try{
            server.getExecutor();
        }catch(final UnsupportedOperationException ignored){
            Assert.fail("Supported operation executor was blocked");
        }
    }

    @Test
    public void testInvalid() throws IOException{
        final SimpleHttpServer server = SimpleHttpServer.create();
        final SimpleHttpServer unmod = new SimpleHttpServerUnmodifiable(server);

        final Runnable[] testMethods = new Runnable[]{
            unmod::getHttpServer,
            () -> {
                try{
                    unmod.bind(null);
                }catch(final IOException ignored){
                    Assert.fail("Unmodifiable server was allowed to attempt bind");
                }
            },
            () -> {
                try{
                    unmod.bind(null,-1);
                }catch(final IOException ignored){
                    Assert.fail("Unmodifiable server was allowed to attempt bind");
                }
            },
            () -> unmod.setExecutor(null),
            () -> unmod.setHttpSessionHandler(null),
            unmod::getHttpSessionHandler,
            () -> unmod.getHttpSession((HttpExchange) null),
            () -> unmod.getHttpSession((SimpleHttpExchange) null),
            unmod::start,
            unmod::stop,
            () -> unmod.stop(-1)
        };

        for(final Runnable method : testMethods){
            try{
                method.run();
                Assert.fail("An unsupported operation ran without permission");
            }catch(final UnsupportedOperationException ignored){
            }
        }
    }

    @Test
    public void testLimitedContextAccess() throws IOException{
        final String blockedContext = "blocked";
        final SimpleHttpServer server = SimpleHttpServer.create();
        final SimpleHttpServer unmod = new SimpleHttpServerUnmodifiable(server);

        server.createContext(blockedContext);

        // get
        Assert.assertNull("Unmodifiable server should not have access to contexts it didn't create",unmod.getContextHandler(blockedContext));

        Assert.assertTrue("Unmodifiable server with no contexts created should not have any viewable",unmod.getContexts().isEmpty());

        // remove
        unmod.removeContext(blockedContext);
        Assert.assertEquals("Unmodifiable server should not be able to remove contexts not created by itself", 1, server.getContexts().size());

        try{
            unmod.createContext(blockedContext);
            Assert.fail("Unmodifiable server should not be able to create contexts already occupied by the server");
        }catch(final IllegalArgumentException ignored){ }

        // creation
        final String context = unmod.getRandomContext();

        try{
            unmod.createContext(context);
        }catch(final IllegalArgumentException ignored){
            Assert.fail("Random context generated by unmodified server should be valid");
        }
        Assert.assertEquals("Unmodified server after created context should have size of 1",1, unmod.getContexts().size());

        unmod.removeContext(context);
        Assert.assertTrue("Removal of only context by unmodified server should be empty",unmod.getContexts().isEmpty());
    }

}
